---
 - name: "création utilisateur"
   user:
            name: "nouveaucompte"
            password: '*'
            groups:
                  - sudo
                  - itescia
            state: present 
            createhome: yes
            home: /home/nouveaucompte
